### ISSUE TITLE
Problems with typography

### ISSUE THREAD

**Issue by ribeiroevandro** [LFeh/kratos-boilerplate#3]
When the user mixin font(), passing as parameter the weight using numbers, it is not being applied to the CSS generated only works when bold step as a parameter. I do not know if I was clear, but below is an example.
```css
// font
p
  font(p2, 500)

// source
p {
    font-size: 1.6rem;
    line-height: 2.4rem;
}

or 

// font
p
  font(p2, bold)

// source
.article p {
    font-size: 1.6rem;
    line-height: 2.4rem;
    font-weight: 700;
}
```
